# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    
    - name: Build core
      run: cd core && go build -v ./... 
    - name: Build api
      run: cd api && go build -v ./...
    - name: Test core
      run: cd core && go test -v ./...
    - name: Test api
      run: cd api && go test -v ./...
